import fs from "fs"
import path from "path"
import ArticleMarquee, { Article } from "@/components/ArticleMarquee"
import EffectsLayer from "@/components/EffectsLayer"
import { SourceChart } from "@/components/SourceChart"

export default async function Home() {
  // Read dynamic json generated by the python pipeline (Level 3 tool)
  let articles: Article[] = [];
  try {
    const dataPath = path.join(process.cwd(), "public", "data", "articles.json");
    const doc = fs.readFileSync(dataPath, "utf-8");
    const json = JSON.parse(doc);
    articles = json.articles || [];
  } catch (error) {
    console.error("Failed to load articles.json. Ensure python pipeline has run.", error);
  }

  return (
    <main className="flex min-h-screen flex-col items-center justify-between relative overflow-hidden">
      {/* Strict Client-Side Global Canvas */}
      <EffectsLayer />
      
      {/* Marquee Header / Main Column */}
      <div className="w-full relative">
        <div className="absolute top-6 right-6 z-50">
          <a href="/dashboard/index.html" className="backdrop-blur-md bg-black/40 border border-white/10 hover:border-[#BFF549] text-white hover:text-[#BFF549] text-xs font-bold tracking-widest px-4 py-2 rounded-full transition-all">
            LEGACY VIEW
          </a>
        </div>
        <ArticleMarquee articles={articles} />
      </div>

      {/* Footer Grid / Visualization */}
      <div className="w-full max-w-7xl mx-auto px-6 lg:px-0 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 pb-32 relative z-10">
        <div className="lg:col-span-1 border border-white/10 rounded-2xl p-0 overflow-hidden relative group h-[400px]">
          <div className="absolute inset-0 bg-black/60 pointer-events-none group-hover:bg-black/30 transition-all duration-500 z-10" />
          <SourceChart articles={articles} />
        </div>
        
        <div className="lg:col-span-2 flex flex-col justify-center border border-white/5 bg-white/5 backdrop-blur-md rounded-2xl p-10 h-full min-h-[400px]">
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tighter mb-6 bg-gradient-to-r from-white to-neutral-400 bg-clip-text text-transparent">Powering the Future.</h2>
          <p className="text-xl text-neutral-300 leading-relaxed max-w-xl">
            B.L.A.S.T aggregates and harmonizes disparate signals from leading industry voices, cutting through the noise and delivering raw, actionable intelligence directly to your terminal.
          </p>
          <div className="mt-8 flex items-center gap-4">
             <div className="w-16 h-1 rounded-full bg-[#BFF549] scale-x-0 origin-left animate-[scale-x_1s_ease-out_forwards_1s]" />
             <span className="text-sm font-mono tracking-widest uppercase text-[#BFF549]">System Online</span>
          </div>
        </div>
      </div>
    </main>
  );
}
